# Generated by Django 5.1.15 on 2026-08-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=24, unique=True)),
                ('ts', models.DateTimeField()),
                ('source', models.CharField(max_length=24)),
                ('rider', models.CharField(max_length=64)),
                ('route', models.CharField(blank=True, max_length=80)),
                ('body', models.TextField()),
            ],
            options={
                'ordering': ['-ts'],
            },
        ),
        migrations.CreateModel(
            name='TriageRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.CharField(max_length=32)),
                ('model', models.CharField(blank=True, max_length=64)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('result', models.JSONField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
