# Generated by Django 5.1.15 on 2026-08-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmessage',
            name='star_rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
